module Exercise5 where

import SetOrd
import Lecture3
import Data.List(isInfixOf)

-- Testing correctness of subformulae implementation.
-- In the comments of this exercise f refers to the original formula,
-- F refers to the set of sub-formulae of f, f' refers to a sub-formula in F.
--
-- We can show that the sub implementation is correct by testing if a number
-- of properties of sub-formulae hold for the sub-formulae generated
-- by the sub implementation.
--
-- Properties of the set of sub-formulae F of a given formula f are:
-- - The size of F equals (amount of atoms in f + amount of operators in f).
-- - Each sub-formula f' in F is a substring of f.
-- - F contains at least each atom as a sub-formula.
-- - F contians at least f itself as a sub-formula.
-- - F contains no duplicates (this is actually already enforced by
--   the set implementation of SetOrd).

type Name = Int

-- Extension to SetOrd:
-- Take the i'th element of an ordered set.
takeISet :: Eq a => Int -> Set a -> a
takeISet i (Set xs) = last (take i xs)

-- Generate sub-formulae of a given formula.
-- This implementation comes from Lab3.html.
sub :: Form -> Set Form
sub (Prop x) = Set [Prop x]
sub (Neg f) = unionSet (Set [Neg f]) (sub f)
sub f@(Cnj [f1,f2]) = unionSet ( unionSet (Set [f]) (sub f1)) (sub f2)
sub f@(Dsj [f1,f2]) = unionSet ( unionSet (Set [f]) (sub f1)) (sub f2)
sub f@(Impl f1 f2) = unionSet ( unionSet (Set [f]) (sub f1)) (sub f2)
sub f@(Equiv f1 f2) = unionSet ( unionSet (Set [f]) (sub f1)) (sub f2)

-- Tests if the size of F equals the amount of atoms in f +
-- the amount of operators in f.
-- propSize :: Form -> Bool
-- propSize f = 

-- Helper function for propSubstring.
-- Tests if one sub-formula f' is a substring of f.
subformula :: Form -> Form -> Bool
subformula f' f = show f' `isInfixOf` show f

-- Tests if the n'th sub-formula f' in F is a substring of f.
propSubstring :: Int -> Form -> Bool
propSubstring n f = subformula (takeISet n (sub f)) f

-- Tests if F contains at least each atom as a sub-formula.
-- propAtoms :: Form -> Bool
-- propAtoms =

-- Tests if F contians f as a sub-formula.
propSelf :: Form -> Bool
propSelf f = inSet f (sub f)


exercise5 :: IO ()
exercise5 = do
    putStrLn "\n--- Exercise 3 ---\n\n"
    putStrLn "We can show that the sub implementation is correct by testing \
    \if a number of properties of sub-formulae hold for the sub-formulae \
    \generated by the sub implementation.\n\
    \Properties of the set of sub-formulae F of a given formula f are:\n\
    \- The size of F equals (amount of atoms in f + amount of operators in f).\n\
    \- Each sub-formula f' in F is a substring of f.\n\
    \- F contains at least each atom as a sub-formula.\n\
    \- F contians at least f itself as a sub-formula.\n\
    \- F contains no duplicates (this is actually already enforced by the set\
    \implementation of SetOrd)."
    print $ sub form1
    print $ sub form2
    print $ sub form3

    --print propSize
    print $ and [x | y <- [1..10], let x = propSubstring y form1]
    --print propAtoms
    print $ propSelf form1